inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false

Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Description: 'Checks that `required_ruby_version` of gemspec is specified and equal to `TargetRubyVersion` of .rubocop.yml.'
  Enabled: true
  VersionAdded: '0.52'
  VersionChanged: '1.22'
  Include:
    - '**/*.gemspec'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 15

Naming/AccessorMethodName:
  Exclude:
    - 'lib/ruby_calendar/calendar.rb'

Naming/MethodParameterName:
  Exclude:
    - 'lib/ruby_calendar/month.rb'
    - 'lib/ruby_calendar/year.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/ruby_calendar/calendar.rb'
